In [ ]:
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn import datasets

iris = datasets.load_iris()
X = iris.data[:,:4]
y = iris.target

(num_samples, num_features) = X.shape
print("num_samples, num_features =", X.shape)

num_samples, num_features = (150, 4)


In [ ]:
from sklearn import preprocessing
Xs = preprocessing.scale(X)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(Xs, y, test_size=0.5, random_state=10)
print(Xs.shape)
print(X_train.shape)
print(X_test.shape)

from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(random_state=0)
clf.fit(X_train, y_train)

(150, 4)
(75, 4)
(75, 4)


LogisticRegression(random_state=0)

In [ ]:
y_pred_train = clf.predict(X_train)
y_pred_test = clf.predict(X_test)
train_acc = np.mean(y_train == y_pred_train)
test_acc = np.mean(y_test == y_pred_test)

print(f"The train accuracy is: {train_acc}")
print(f"The test accuracy is: {test_acc}")

The train accuracy is: 0.9866666666666667
The test accuracy is: 0.96
accuracy is much higher with all 4 characteristics than with only 2


In [ ]:
yhat_probs_test = clf.predict_proba(X_test)
np.set_printoptions(precision=2, suppress=True)

print(y_pred_test.shape, yhat_probs_test.shape)
print(np.hstack([y_pred_test.reshape(-1,1), yhat_probs_test]))

(75,) (75, 3)
[[1.   0.   0.76 0.24]
 [2.   0.   0.15 0.85]
 [0.   0.98 0.02 0.  ]
 [1.   0.03 0.69 0.27]
 [0.   0.96 0.04 0.  ]
 [1.   0.02 0.93 0.05]
 [2.   0.   0.49 0.5 ]
 [1.   0.05 0.89 0.06]
 [0.   0.96 0.04 0.  ]
 [1.   0.04 0.74 0.22]
 [1.   0.06 0.61 0.32]
 [2.   0.   0.17 0.83]
 [1.   0.01 0.81 0.17]
 [0.   0.9  0.1  0.  ]
 [0.   0.99 0.01 0.  ]
 [2.   0.   0.08 0.92]
 [1.   0.12 0.57 0.31]
 [0.   0.95 0.05 0.  ]
 [0.   0.98 0.02 0.  ]
 [0.   0.95 0.05 0.  ]
 [2.   0.   0.05 0.95]
 [2.   0.   0.05 0.95]
 [2.   0.   0.32 0.68]
 [0.   0.97 0.03 0.  ]
 [1.   0.05 0.71 0.24]
 [0.   0.96 0.04 0.  ]
 [1.   0.11 0.78 0.1 ]
 [1.   0.03 0.8  0.17]
 [1.   0.   0.66 0.33]
 [2.   0.   0.02 0.98]
 [1.   0.01 0.77 0.21]
 [1.   0.03 0.81 0.16]
 [2.   0.   0.25 0.74]
 [2.   0.   0.04 0.96]
 [2.   0.   0.19 0.81]
 [0.   0.97 0.03 0.  ]
 [2.   0.   0.07 0.92]
 [2.   0.   0.04 0.96]
 [2.   0.   0.01 0.99]
 [2.   0.   0.08 0.92]
 [0.   0.96 0.04 0.  ]
 [0.   0.96 0.04 0.  ]
 [1.   0.08 0.76 0.1

In [ ]:
sum = 0
counter = 0
counter1 = 0
for x in yhat_probs_test:
  ##for z in y_pred_test:
    sum += x[y_pred_test[counter1]]
    counter += 1
    counter1 += 1

print("average prob: "+str(sum/counter))

average prob: 0.8448627693757357
